## ExampleUI - Config!!!

## ExampleUI - TextUI

example.title: "§9§lExampleUI§r"
example.content: "§7Dies ist der §c§lContent§r §7von der §9§lExampleUI§r"
example.button1: "§71. Klick§r"
example.button2: "§72. Klick§r"
example.button3: "§73. Klick§r"

## ExampleUI - Messages

example.msg1: "§71. Nachricht vom §c1. Klick§r"
example.msg2: "§72. Nachricht vom §c2. Klick§r"
example.msg3: "§73. Nachricht vom §c3. Klick§r"

## Habt Spaß :)
