## ExampleUI - Config!!!

## ExampleUI - TextUI

example.title: "§9§lExampleUI§r"
example.content: "§7this is the §c§lContent§r §7of the §9§lExampleUI§r"
example.button1: "§71st click§r"
example.button2: "§72nd click§r"
example.button3: "§73rd click§r"

## ExampleUI - Messages

example.msg1: "§71. Message from §c1st click§r"
example.msg2: "§72. Message from §c2nd click§r"
example.msg3: "§73. Message from §c3rd click§r"

## Have fun :)
